### ISSUE TITLE
В отчет Акт сверки добавить возможность скрыть/не отображать корректировки долгов

### ISSUE THREAD

**Issue by vizirina** [Nullarity/n5#580]

**Comment by grumagargler** [comment]
Накидайте пожалуйста пример, когда это не нужно делать. Дело в том, что сейчас (в последнем релизе) при формировании акта без детализации по договорам, корректировки между договорами внутри контрагента не должны выводиться. Во всех остальных случаях невыводить нельзя, без искажения долга.

**Comment by Nullarity** [comment]
Накидайте пожалуйста пример, когда это не нужно делать. Дело в том, что сейчас (в последнем релизе) при формировании акта без детализации по договорам, корректировки между договорами внутри контрагента не должны выводиться. Во всех остальных случаях невыводить нельзя, без искажения долга.

**Comment by vizirina** [comment]
Добрый день. Возможность выбора не детализировать по договорам и имелась ввиду. Просто на момент сообщения на гитхабе база еще не была обновлена на последний релиз. Протестирую и отпишусь. Спасибо
07.11.2022, 14:13, grumagargler < ***@***.*** ***@***.*** >
Накидайте пожалуйста пример, когда это не нужно делать. Дело в том, что сейчас (в последнем релизе) при формировании акта без детализации по договорам, корректировки между договорами внутри контрагента не должны выводиться. Во всех остальных случаях невыводить нельзя, без искажения долга.
