### ISSUE TITLE
По каким причинам некоторые пользователи не видят других? например, в Календаре нет возможности выбрать искомого Исполнителя

### ISSUE THREAD

**Issue by SvetlanaRes** [Nullarity/n5#695]
@Nullarity какие настройки в правах или ролях могут быть установлены, что другие не видят этого пользователя?

**Comment by SvetlanaRes** [comment]
@Nullarity какие настройки в правах или ролях могут быть установлены, что другие не видят этого пользователя?

**Comment by Nullarity** [comment]
Если пользователь (справочник Пользователи) является системным администратором, то его профиль скрывается от всех пользователей. Подробнее https://nullarity.com/users/#_2

Если речь о выборе сотрудника (справочник Сотрудники), то текущий пользователь может видеть только тех сотрудников, с которыми у него общие проекты (т.е. находятся в списке исполнителей).

**Comment by SvetlanaRes** [comment]
Ситуация 1: Мой пользователь - НЕ сис.админ => в Календаре не вижу всех Исполнителей, а пишет "объект не обнаружен". Указываю себя как сис.админ - вижу всех.
Ситуация 2: Есть пользователи, которые должны видеть всех Пользователей/Исполнителей, но сис.админами не являются, как тогда настроить? где и что указать? (к сожалению, help не помог).
Подскажите, пожалуйста

**Comment by SvetlanaRes** [comment]
![image](https://github.com/Nullarity/n5/assets/82224240/a86262dd-3867-4173-80e8-0289b38e3e9e)
Например, я - НЕ сис.админ. (сняла флаг в конфигураторе) и не вижу некоторых пользователей, из списка пользователей не могу выбрать.
Вопрос: как и что надо настроить так, чтоб пользователь не был сис.админом, но мог видеть других пользователей?
Это необходимо для работы менеджерам и руководителям проектных групп.
Не понимаю, почему некоторые видны всем, другие нет.

**Comment by SvetlanaRes** [comment]
еще прикол - если пользователь не сис.админ, то себя не видит. Записи с его именем видит исполнителя как "объект не обнаружен...". При попытки сформировать Запись подставляется другой исполнитель, при попытки перевыбрать - в списке нет его пользователя.
с чем может быть связано? где и что может быть указано не так?

**Comment by Nullarity** [comment]
> Например, я - НЕ сис.админ. (сняла флаг в конфигураторе)

Тут есть проблема. Нужно сисадминство убирать из приложения. Верните в конфигураторе галку на место, закройте его, и уберите сисадминство в режиме предприятия. Проделайте это для всех пользователей, с ролями которых работали напрямую через конфигуратор. В этом случае, программа на прикладном будет распознавать роли. После этих действий, скажите, изменилось ли что-то в календаре.
