### ISSUE TITLE
Реализация ТМЦ на основании заказа

### ISSUE THREAD

**Issue by vizirina** [Nullarity/n5#704]
Для выписки Налоговой накладной на товар/продукцию необходимо сделать реализацию ТМЦ  из Заказа Покупателя. После отправки на утверджение, система формирует процесс отгрузки. После завершения процесса отгрузки цепочка прерывается - ни в документе Отгрузка, ни в Заказе покупателя связанной операции для Реализации нет,  только в элементе Котрагент через кнопку Реализация, что не совсем удобно

**Comment by Nullarity** [comment]
Я проанализирую ситуацию о отпишусь позже.

**Comment by vizirina** [comment]
Спасибо

**Comment by SvetlanaRes** [comment]
@Nullarity вопрос снимается.
Разобрались благодаря информационному порталу www.nullarity.com 
Спасибо.

**Comment by vizirina** [comment]
Спасибо, извините за беспокойство на ровном месте
